name: Docker Image CI

on:
  push:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Publish Docker
      uses: elgohr/Publish-Docker-Github-Action@3.04
      with:
        name: openthisworld/apache2:$(date +%s)
        username: openthisworld
        password: ${{ secrets.DOCKER_PASSWORD }}
        tags: "test"
